In [3]:
import numpy as np
import pandas as pd

from importSleepAccel import import_sleep_accel

accel, hr, stage = import_sleep_accel("../Data/SleepAccel", "7749105")


In [7]:
accel

[(array([0.5325623, 0.3649445, 0.2610779, ..., 0.0861359, 0.134613 ,
         0.1610107], shape=(1500,)),
  array([1.1168671, 1.1997681, 1.2088318, ..., 0.9072571, 0.8970947,
         0.8689117], shape=(1500,)),
  array([ 0.0313263, -0.0036774,  0.0573425, ...,  0.4497681,  0.4783936,
          0.4483643], shape=(1500,))),
 (array([0.0150452, 0.0510559, 0.0359802, ..., 0.2901154, 0.4257965,
         0.7276917], shape=(1500,)),
  array([0.6204987, 0.6702118, 0.7070465, ..., 0.381897 , 0.3840485,
         0.3612823], shape=(1500,)),
  array([ 0.3233795,  0.4131317,  0.4972992, ..., -0.1930695, -0.1821289,
         -0.1585693], shape=(1500,))),
 (array([ 0.0440674,  0.052475 ,  0.0387726, ..., -0.0739899, -0.0807953,
         -0.0478668], shape=(1500,)),
  array([-0.5457458, -0.5379028, -0.5118866, ..., -0.2847137, -0.2016449,
         -0.2060242], shape=(1500,)),
  array([-0.861908 , -0.8701019, -0.8846588, ..., -0.9267426, -0.9567261,
         -0.9522705], shape=(1500,))),
 (array([ 0.0

In [6]:
hr

[array([69, 69, 69, 70]),
 array([ 71, 101, 100, 100]),
 array([100, 100, 100,  90,  90,  95]),
 array([73, 86, 86, 88]),
 array([88, 83, 82, 82, 82, 82]),
 array([92, 92, 92, 92, 91]),
 array([77, 77, 77, 77, 77, 78]),
 array([78, 78, 78, 78, 78, 78]),
 array([78, 78, 79, 79, 79]),
 array([80, 79, 79, 78, 78, 77]),
 array([72, 72, 72, 77, 77, 75]),
 array([74, 74, 73, 74, 72, 72]),
 array([74, 75, 75, 75, 76, 74]),
 array([75, 74, 74, 77, 77]),
 array([76, 76, 76, 76, 77, 79]),
 array([79, 77, 77, 77, 83, 82]),
 array([81, 80, 84, 86, 86]),
 array([86, 86, 86, 89, 89, 91, 91]),
 array([92, 98, 99, 99, 98]),
 array([91, 86, 86, 86, 86, 86]),
 array([86, 86, 87, 86, 86, 87]),
 array([87, 86, 86, 86, 86]),
 array([87, 86, 86, 81, 80, 80]),
 array([80, 80, 81, 81]),
 array([82, 82, 82, 82, 82, 85, 85]),
 array([78, 78, 80, 78, 78]),
 array([78, 75, 74, 73, 67, 68]),
 array([68, 68, 67, 66, 66]),
 array([68, 68, 69, 69, 67, 67, 67]),
 array([66, 64, 63, 63, 67]),
 array([65, 65, 65, 65, 65

In [8]:
stage

[-1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,